In [7]:
import pandas as pd

df = pd.read_parquet("/content/team_5 (4).parquet")

print("Shape:", df.shape)

print("\nColumns:")
print(df.columns.tolist())

print("\nData Types:")
print(df.dtypes)

df.head()

Shape: (8844800, 22)

Columns:
['station_id', 'state', 'city', 'station_name', 'timestamp', 'datetime', 'at_c', 'rh_percent', 'ws_m_s', 'wd_deg', 'rf_mm', 'tot_rf_mm', 'sr_w_mt2', 'bp_mmhg', 'vws_m_s', 'pollutant', 'value', 'station', 'year', 'month', 'day', 'hour']

Data Types:
station_id                   object
state                        object
city                         object
station_name                 object
timestamp                    object
datetime        datetime64[us, UTC]
at_c                        float64
rh_percent                  float64
ws_m_s                      float64
wd_deg                      float64
rf_mm                       float64
tot_rf_mm                   float64
sr_w_mt2                    float64
bp_mmhg                     float64
vws_m_s                     float64
pollutant                    object
value                       float64
station                      object
year                          int32
month                         int32
day                           int32
hour                          int32
dtype: object

,station_id,state,city,station_name,timestamp,datetime,at_c,rh_percent,ws_m_s,wd_deg,...,sr_w_mt2,bp_mmhg,vws_m_s,pollutant,value,station,year,month,day,hour
0,site_1424,Delhi,Delhi,"Jawaharlal Nehru Stadium, Delhi - DPCC",2024-01-01T00:00:00.000000+0000,2024-01-01 00:00:00+00:00,10.3,80.0,1.1,79.0,...,5.0,987.2,NaN,benzene,1.70,"Jawaharlal Nehru Stadium, Delhi - DPCC",2024,1,1,0
1,site_107,Delhi,Delhi,"Pusa, Delhi - IMD",2024-01-01T00:00:00.000000+0000,2024-01-01 00:00:00+00:00,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,co,2.34,"Pusa, Delhi - IMD",2024,1,1,0
2,site_122,Delhi,Delhi,"Mandir Marg, Delhi - DPCC",2024-01-01T00:00:00.000000+0000,2024-01-01 00:00:00+00:00,9.3,85.6,0.6,182.8,...,4.6,975.8,0.0,benzene,1.10,"Mandir Marg, Delhi - DPCC",2024,1,1,0
3,site_122,Delhi,Delhi,"Mandir Marg, Delhi - DPCC",2024-01-01T00:00:00.000000+0000,2024-01-01 00:00:00+00:00,9.3,85.6,0.6,182.8,...,4.6,975.8,0.0,nh3,81.60,"Mandir Marg, Delhi - DPCC",2024,1,1,0
4,site_122,Delhi,Delhi,"Mandir Marg, Delhi - DPCC",2024-01-01T00:00:00.000000+0000,2024-01-01 00:00:00+00:00,9.3,85.6,0.6,182.8,...,4.6,975.8,0.0,no,40.30,"Mandir Marg, Delhi - DPCC",2024,1,1,0

In [8]:
df.shape

(8844800, 22)

In [9]:
df.columns.tolist()

['station_id',
 'state',
 'city',
 'station_name',
 'timestamp',
 'datetime',
 'at_c',
 'rh_percent',
 'ws_m_s',
 'wd_deg',
 'rf_mm',
 'tot_rf_mm',
 'sr_w_mt2',
 'bp_mmhg',
 'vws_m_s',
 'pollutant',
 'value',
 'station',
 'year',
 'month',
 'day',
 'hour']

In [10]:
# Missing values
df.isnull().sum().sort_values(ascending=False)

vws_m_s         6546511
rf_mm           4006105
bp_mmhg         3022601
at_c            2532923
wd_deg          1836378
sr_w_mt2        1610725
ws_m_s          1531562
rh_percent      1519086
tot_rf_mm        801929
timestamp             0
state                 0
station_id            0
station_name          0
city                  0
datetime              0
pollutant             0
value                 0
station               0
year                  0
month                 0
day                   0
hour                  0
dtype: int64

In [11]:
# Missing value percentages
(df.isnull().sum() / len(df) * 100).sort_values(ascending=False)

vws_m_s         74.015365
rf_mm           45.293336
bp_mmhg         34.173763
at_c            28.637425
wd_deg          20.762233
sr_w_mt2        18.210983
ws_m_s          17.315960
rh_percent      17.174905
tot_rf_mm        9.066672
timestamp        0.000000
state            0.000000
station_id       0.000000
station_name     0.000000
city             0.000000
datetime         0.000000
pollutant        0.000000
value            0.000000
station          0.000000
year             0.000000
month            0.000000
day              0.000000
hour             0.000000
dtype: float64

In [12]:
# Duplicate rows
df.duplicated().sum()

np.int64(0)

In [13]:
# Basic statistics
df.describe()

,at_c,rh_percent,ws_m_s,wd_deg,rf_mm,tot_rf_mm,sr_w_mt2,bp_mmhg,vws_m_s,value,year,month,day,hour
count,6.311877e+06,7.325714e+06,7.313238e+06,7.008422e+06,4.838695e+06,8.042871e+06,7.234075e+06,5.822199e+06,2.298289e+06,8.844800e+06,8.844800e+06,8.844800e+06,8.844800e+06,8.844800e+06
mean,2.537028e+01,6.343575e+01,9.463776e-01,1.878149e+02,2.911537e-02,1.751618e-02,9.737695e+01,9.661260e+02,4.091814e-03,4.852304e+01,2.024491e+03,6.460703e+00,1.574152e+01,1.160196e+01
std,7.892679e+00,2.033017e+01,1.028551e+00,8.810058e+01,6.140375e-01,4.764835e-01,1.484373e+02,6.256258e+01,7.317365e-01,8.231834e+01,4.999121e-01,3.475529e+00,8.797462e+00,6.892201e+00
min,7.000000e-01,6.200000e-01,1.000000e-02,1.000000e-02,0.000000e+00,0.000000e+00,2.000000e-01,7.000000e+02,-9.950000e+00,0.000000e+00,2.024000e+03,1.000000e+00,1.000000e+00,0.000000e+00
25%,1.910000e+01,4.700000e+01,3.000000e-01,1.390000e+02,0.000000e+00,0.000000e+00,5.000000e+00,9.770000e+02,-2.000000e-02,2.600000e+00,2.024000e+03,3.000000e+00,8.000000e+00,6.000000e+00
50%,2.710000e+01,6.500000e+01,6.000000e-01,1.890000e+02,0.000000e+00,0.000000e+00,1.760000e+01,9.830000e+02,-1.000000e-02,1.618000e+01,2.024000e+03,6.000000e+00,1.600000e+01,1.200000e+01
75%,3.120000e+01,8.100000e+01,1.200000e+00,2.460000e+02,0.000000e+00,0.000000e+00,1.320000e+02,9.860000e+02,1.000000e-01,5.434000e+01,2.025000e+03,1.000000e+01,2.300000e+01,1.800000e+01
max,4.990000e+01,9.900000e+01,2.160000e+01,3.600000e+02,5.000000e+01,5.000000e+01,1.987000e+03,1.002900e+03,3.810000e+00,1.000000e+03,2.025000e+03,1.200000e+01,3.100000e+01,2.300000e+01

In [14]:
# Missing value summary

missing_counts = df.isnull().sum()

missing_percent = (
    df.isnull().sum() / len(df) * 100
)

validation_report = pd.DataFrame({
    "missing_count": missing_counts,
    "missing_percent": missing_percent
})

validation_report.sort_values(
    by="missing_percent",
    ascending=False
)

              missing_count  missing_percent
vws_m_s             6546511        74.015365
rf_mm               4006105        45.293336
bp_mmhg             3022601        34.173763
at_c                2532923        28.637425
wd_deg              1836378        20.762233
sr_w_mt2            1610725        18.210983
ws_m_s              1531562        17.315960
rh_percent          1519086        17.174905
tot_rf_mm            801929         9.066672
timestamp                 0         0.000000
state                     0         0.000000
station_id                0         0.000000
station_name              0         0.000000
city                      0         0.000000
datetime                  0         0.000000
pollutant                 0         0.000000
value                     0         0.000000
station                   0         0.000000
year                      0         0.000000
month                     0         0.000000
day                       0         0.000000
hour                      0         0.000000

In [15]:
validation_report.to_csv(
    "validation_report.csv"
)

In [17]:
# Temperature

print(
    "Temperature below -20:",
    (df["at_c"] < -20).sum()
)

print(
    "Temperature above 60:",
    (df["at_c"] > 60).sum()
)

Temperature below -20: 0
Temperature above 60: 0

In [18]:
# Humidity

print(
    "Humidity below 0:",
    (df["rh_percent"] < 0).sum()
)

print(
    "Humidity above 100:",
    (df["rh_percent"] > 100).sum()
)

Humidity below 0: 0
Humidity above 100: 0

In [19]:
# Wind speed

print(
    "Negative wind speed:",
    (df["ws_m_s"] < 0).sum()
)

Negative wind speed: 0

In [20]:
# Rainfall

print(
    "Negative rainfall:",
    (df["rf_mm"] < 0).sum()
)

Negative rainfall: 0

In [21]:
print("Temperature below -20:", (df["at_c"] < -20).sum())
print("Temperature above 60:", (df["at_c"] > 60).sum())

print("Humidity below 0:", (df["rh_percent"] < 0).sum())
print("Humidity above 100:", (df["rh_percent"] > 100).sum())

print("Negative wind speed:", (df["ws_m_s"] < 0).sum())

print("Negative rainfall:", (df["rf_mm"] < 0).sum())

Temperature below -20: 0
Temperature above 60: 0
Humidity below 0: 0
Humidity above 100: 0
Negative wind speed: 0
Negative rainfall: 0

Data Cleaning

In [22]:
# Create a copy

clean_df = df.copy()

# Missing values before cleaning

print("Missing values BEFORE cleaning:")
print(clean_df.isnull().sum())

Missing values BEFORE cleaning:
station_id            0
state                 0
city                  0
station_name          0
timestamp             0
datetime              0
at_c            2532923
rh_percent      1519086
ws_m_s          1531562
wd_deg          1836378
rf_mm           4006105
tot_rf_mm        801929
sr_w_mt2        1610725
bp_mmhg         3022601
vws_m_s         6546511
pollutant             0
value                 0
station               0
year                  0
month                 0
day                   0
hour                  0
dtype: int64

In [23]:
# Fill missing values using median

columns_to_fill = [
    "at_c",
    "rh_percent",
    "ws_m_s",
    "wd_deg",
    "rf_mm",
    "tot_rf_mm",
    "sr_w_mt2",
    "bp_mmhg",
    "vws_m_s"
]

for col in columns_to_fill:
    clean_df[col] = clean_df[col].fillna(
        clean_df[col].median()
    )

In [24]:
print("Missing values AFTER cleaning:")
print(clean_df.isnull().sum())

Missing values AFTER cleaning:
station_id      0
state           0
city            0
station_name    0
timestamp       0
datetime        0
at_c            0
rh_percent      0
ws_m_s          0
wd_deg          0
rf_mm           0
tot_rf_mm       0
sr_w_mt2        0
bp_mmhg         0
vws_m_s         0
pollutant       0
value           0
station         0
year            0
month           0
day             0
hour            0
dtype: int64

In [25]:
clean_df.isnull().sum()

station_id      0
state           0
city            0
station_name    0
timestamp       0
datetime        0
at_c            0
rh_percent      0
ws_m_s          0
wd_deg          0
rf_mm           0
tot_rf_mm       0
sr_w_mt2        0
bp_mmhg         0
vws_m_s         0
pollutant       0
value           0
station         0
year            0
month           0
day             0
hour            0
dtype: int64

Data Transformation

In [26]:
clean_df["datetime"] = pd.to_datetime(clean_df["datetime"])

clean_df["weekday"] = clean_df["datetime"].dt.day_name()

clean_df["is_weekend"] = clean_df["weekday"].isin(
    ["Saturday", "Sunday"]
).astype(int)

clean_df[["datetime", "weekday", "is_weekend"]].head()

                   datetime weekday  is_weekend
0 2024-01-01 00:00:00+00:00  Monday           0
1 2024-01-01 00:00:00+00:00  Monday           0
2 2024-01-01 00:00:00+00:00  Monday           0
3 2024-01-01 00:00:00+00:00  Monday           0
4 2024-01-01 00:00:00+00:00  Monday           0

In [28]:
clean_df["quarter"] = clean_df["datetime"].dt.quarter

clean_df[["month", "quarter"]].head()

   month  quarter
0      1        1
1      1        1
2      1        1
3      1        1
4      1        1

In [29]:
def get_season(month):
    if month in [12, 1, 2]:
        return "Winter"
    elif month in [3, 4, 5]:
        return "Summer"
    elif month in [6, 7, 8, 9]:
        return "Monsoon"
    else:
        return "Post-Monsoon"

clean_df["season"] = clean_df["month"].apply(get_season)

clean_df["season"].value_counts()

season
Monsoon         2859163
Summer          2268103
Winter          2244163
Post-Monsoon    1473371
Name: count, dtype: int64

In [30]:
clean_df[["weekday","is_weekend"]].head()

  weekday  is_weekend
0  Monday           0
1  Monday           0
2  Monday           0
3  Monday           0
4  Monday           0

In [31]:
clean_df["season"].value_counts()

season
Monsoon         2859163
Summer          2268103
Winter          2244163
Post-Monsoon    1473371
Name: count, dtype: int64

# Data Quality Report

In [32]:
quality_report = {
    "Total Rows": len(df),
    "Duplicate Rows": df.duplicated().sum(),
    "Columns with Missing Values": (df.isnull().sum() > 0).sum(),
    "Total Missing Values Before Cleaning": df.isnull().sum().sum(),
    "Total Missing Values After Cleaning": clean_df.isnull().sum().sum()
}

for key, value in quality_report.items():
    print(f"{key}: {value}")

Total Rows: 8844800
Duplicate Rows: 0
Columns with Missing Values: 9
Total Missing Values Before Cleaning: 23407820
Total Missing Values After Cleaning: 0

# Save Cleaned Dataset

In [33]:
clean_df.to_parquet(
    "cleaned_air_quality.parquet",
    index=False
)

print("Dataset saved successfully")

Dataset saved successfully

In [34]:
transformed_df = clean_df.copy()

transformed_df.to_parquet(
    "transformed_air_quality.parquet",
    index=False
)

print("Transformation dataset saved")

Transformation dataset saved

In [ ]:
# Aggregations

In [35]:
clean_df["date"] = clean_df["datetime"].dt.date

In [ ]:
daily_pollution = (
    clean_df.groupby(
        ["station_id", "date", "pollutant"]
    )["value"]
    .mean()
    .reset_index()
)

daily_pollution.head()

In [42]:
monthly_pollution = (
    clean_df.groupby(
        ["station_id", "year", "month", "pollutant"]
    )["value"]
    .mean()
    .reset_index()
)

monthly_pollution.head()

  station_id  year  month pollutant      value
0   site_105  2024      1   benzene   0.000000
1   site_105  2024      1        co   1.212826
2   site_105  2024      1        no  87.537681
3   site_105  2024      1       no2  48.227788
4   site_105  2024      1     ozone  27.125251

In [49]:
clean_df["date"] = clean_df["datetime"].dt.date

daily_pollution = (
    clean_df.groupby(
        ["station_id", "date", "pollutant"]
    )["value"]
    .mean()
    .reset_index()
)

monthly_pollution = (
    clean_df.groupby(
        ["station_id", "year", "month", "pollutant"]
    )["value"]
    .mean()
    .reset_index()
)

In [50]:
daily_pollution.to_parquet(
    "daily_pollution.parquet",
    index=False
)

monthly_pollution.to_parquet(
    "monthly_pollution.parquet",
    index=False
)

print("Files saved successfully")

Files saved successfully

In [51]:
daily_pollution.shape

(97933, 4)

In [ ]:
monthly_pollution.shape

# Pollution Categorization

In [44]:
def pollution_category(value):
    if value <= 50:
        return "Good"
    elif value <= 100:
        return "Moderate"
    elif value <= 200:
        return "Poor"
    elif value <= 300:
        return "Very Poor"
    else:
        return "Severe"

clean_df["pollution_level"] = clean_df["value"].apply(
    pollution_category
)

clean_df["pollution_level"].value_counts()

pollution_level
Good         6493824
Moderate     1072224
Poor          755934
Very Poor     308515
Severe        214303
Name: count, dtype: int64

In [45]:
clean_df[
    ["pollutant", "value", "pollution_level"]
].head()

  pollutant  value pollution_level
0   benzene   1.70            Good
1        co   2.34            Good
2   benzene   1.10            Good
3       nh3  81.60        Moderate
4        no  40.30            Good

In [46]:
clean_df.to_parquet(
    "final_milestone3_dataset.parquet",
    index=False
)

In [47]:
clean_df["pollution_level"].value_counts()

pollution_level
Good         6493824
Moderate     1072224
Poor          755934
Very Poor     308515
Severe        214303
Name: count, dtype: int64

# Conclusion

A batch data transformation pipeline was developed for the air quality dataset.

The pipeline performed:
- Data profiling
- Data validation
- Missing value treatment
- Feature engineering
- Pollution categorization
- Daily and monthly aggregations

The resulting datasets are analytics-ready and can be loaded into the dimensional data warehouse developed in Milestone 2.